# Site settings
title: Matt Christian
description: 'Data Scientist with 10+ years of experience turning data into actionable insights for complex business problems. Currently working on uncover the upstream manufacturing sites for pharmaceuticals. Domain expertise includes logistics, pharmaceuticals, oil & gas, renewable energy, and federal government consulting. Education: M.S. in Financial Mathematics from Johns Hopkins University, B.S. in Chemical Engineering from the University of Virginia.'
url: 'https://analyticalmeanderings.github.io'
baseurl: ''
google_analytics: 'UA-83225772-1'
disqus_shortname: 'analyticalmeanderings-github-io'

author:
  name: 'Matt Christian'
  email: matthew.bryan.christian@gmail.com
  github_username:  analyticalmeanderings
  linkedin_username:  matthew-christian-17577641

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/index.html
markdown: kramdown
highlighter: rouge

# sass:
#     sass_dir: _sass
#     style: compressed

pattern_styles: css/main.css

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
