# Site settings
title: Matt Christian
description: 'Data Scientist'
url: 'https://analyticalmeanderings.github.io'
baseurl: ''
google_analytics: 'UA-83225772-1'
disqus_shortname: 'analyticalmeanderings-github-io'

author:
  name: 'Matt Christian'
  email: matthew.bryan.christian@gmail.com
  github_username:  analyticalmeanderings
  linkedin_username:  matthew-christian-17577641

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
